version: 2.0

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    machine: true
    steps:
      - checkout
      
      # to move to build
      - run: pwd
      - run: echo "$EC2_KEY" > /home/circleci/project/sef-keys.pem
      - run: cat /home/circleci/project/sef-keys.pem
      - run: chmod 400 /home/circleci/project/sef-keys.pem
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 599570849149.dkr.ecr.us-east-1.amazonaws.com
      
      # leave in test
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)
      - run: docker run --publish 8080:8080 --detach --name project major-project
      - run: docker exec project ./mvnw test
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker build -t frontend .)
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker run -it -d -p 3000:3000 --name frontend-container frontend)
      - run: docker exec frontend-container npm run test -- --watchAll=false
      
      
      # to move to build
      - run: docker tag frontend 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project:front_V1   
      - run: docker tag major-project 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project:back_V1
      - run: docker push 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project
      - run: cd /home/circleci/project/
      - run: ssh -i "sef-keys.pem" ec2-user@ec2-3-88-187-110.compute-1.amazonaws.com "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin http://599570849149.dkr.ecr.us-east-1.amazonaws.com/ && sudo service docker start && docker rm -f $(docker ps -a -q) && docker rmi $(docker images -q) --force && docker pull 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project:back_V1 && docker pull 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project:front_V1 && docker run --publish 8080:8080 --detach --name back_v1 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project && docker run -it -d -p 80:3000 --name front_V1 599570849149.dkr.ecr.us-east-1.amazonaws.com/sef-major-project"

  build:
    machine: true
    steps:
      - checkout
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker build -t frontend .)



workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build