version: 2.0

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: docker build -t major-project
      - run: ./mvnw test

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - setup_remote_docker
      - run: docker build -t major-project
      - run: ./mvnw -Dmaven.test.skip=true package


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build