version: 2.0

jobs:
  test:
    docker:
      - image: major-project
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
          docker build -t major-project
          ./mvnw test

  build:
    docker:
      - image: major-project
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
          docker build -t major-project
          ./mvnw -Dmaven.test.skip=true package


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build