version: 2.0

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)
      - run: docker run --publish 8080:8080 --detach --name project major-project
      - run: docker exec project ./mvnw test
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker build -t frontend .)
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker run -it -d -p 3000:3000 --name frontend-container frontend)
      - run: docker exec frontend-container npm run test -- --watchAll=false
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password 599570849149.dkr.ecr.us-east-1.amazonaws.com
      - run: docker tag frontend:latest 599570849149.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      - run: docker push 599570849149.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      - run: docker tag major-project:latest 599570849149.dkr.ecr.us-east-1.amazonaws.com/major-project:latest
      - run: docker push 599570849149.dkr.ecr.us-east-1.amazonaws.com/major-project:latest

  build:
    machine: true
    steps:
      - checkout
      - run: aws --version
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)
      - run: (cd /home/circleci/project/FrontEnd/frontend-react && docker build -t frontend .)


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build