version: 2.0

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)
      - run: docker run --publish 8080:8080 --detach --name project major-project
      - run: docker exec -d project (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw test)

  build:
    machine: true
    steps:
      - checkout
      - run: echo $(pwd)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && ./mvnw -Dmaven.test.skip=true package)
      - run: (cd /home/circleci/project/BackEnd/MajorProject && docker build -t major-project .)


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build