version: 2.0

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t major-project .
      - run: ./mvnw test

  build:
    machine: true
    steps:
      - checkout
      - run: (cd majorproject-4-wed-18-30-3/BackEnd/MajorProject && chmod +x mvnw)
      - run: (cd majorproject-4-wed-18-30-3/BackEnd/MajorProject && /mvnw -Dmaven.test.skip=true package)
      - run: docker build -t major-project .


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build