version: 2.0

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t major-project .
      - run: ./mvnw test

  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t major-project .
      - run: ./mvnw -Dmaven.test.skip=true package


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build